version: '3.8'

services:
  web:
    depends_on:
      - "db"
    # build: .
    image: gateway:latest
    # command: python gateway_service.py
    ports:
      - 3001:3001
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vector
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    
volumes:
  postgres_data: