version: '3.8'
name: kaleidoscope-staging
services:
  web:
    depends_on:
      - "db"
    build: .
    env_file:
      - .env
    ports:
      - 5001:5001
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
  web-worker:
    depends_on:
      - "db"
    build: .
    entrypoint: celery
    env_file:
      - .env
    command: -A gateway_service.celery worker -B
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=kaleidoscope-staging
    ports:
      - 8001:5432
# nginx:
#   build: ./services/nginx
#   ports:
#     - 1337:80
#   depends_on:
#     - web
    
volumes:
  postgres_data:
