version: '3.8'
name: kaleidoscope-dev-slurm

networks:
  default:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "192.168.0.0/24"
                gateway: "192.168.0.1"

services:
  web:
    depends_on:
      - "db"
    build: .
    entrypoint: ./docker-entrypoint.sh
    env_file:
      - .env
    ports:
      - 4001:3001
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
  web-worker:
    depends_on:
      - "db"
    build: .
    entrypoint: celery
    env_file:
      - .env
    command: -A gateway_service.celery worker -B
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=kaleidoscope-staging
    ports:
      - 8000:5432
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-21-08-6-1}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../model_service:/app
    expose:
      - "6817"
      - 2022:22
    depends_on:
      - "slurmdbd"

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../model_service:/app
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../model_service:/app
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  postgres_data:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:


