version: '3.8'
name: lingua-staging
services:
  web:
    depends_on:
      - "db"
    build: .
    command: gateway_service.py
    env_file:
      - .env
    ports:
      - 8888:3001
    volumes:
      - /h/llm/.ssh:/root/.ssh
  web-worker:
    depends_on:
      - "db"
    build: .
    entrypoint: celery
    env_file:
      - .env
    command: -A gateway_service.celery worker -B
  db:
    image: postgres
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=lingua-staging
    ports:
      - 8000:5432
    
volumes:
  postgres_data_staging:
