# Staging environment
version: '3.8'
name: kaleidoscope-staging
services:
  web:
    depends_on:
      - "db"
    build: .
    env_file:
      - .env
    ports:
      - 4001:4001
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
    restart: always
  web-worker:
    depends_on:
      - "db"
    build: .
    entrypoint: celery
    env_file:
      - .env
    command: -A gateway_service.celery worker -B
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
    restart: always
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=kaleidoscope-staging
    ports:
      - 8000:5432
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 1338:80
    depends_on:
      - web
    restart: always
    
volumes:
  postgres_data:
    name: kaleidoscope-staging_postgres_data
